name: humanhash
description: A human-readable unique ID generator
version: 1.1.0
homepage: https://github.com/johnpryan/humanhash-dart
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=1.20.1 <4.0.0'

dev_dependencies:
  test: ^1.3.0
