name: humanhash
description: A human-readable unique ID generator
version: 2.0.0
repository: https://github.com/johnpryan/humanhash-dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: ^1.3.0
